
const ALLOW_FILE_EXTENSIONS = Bun.env.ALLOW_FILE_EXTENSIONS ? Bun.env.ALLOW_FILE_EXTENSIONS.split(',') : []
const PORT = Bun.env.PORT ?? 4000
const FILE_DESTINATION = Bun.env.FILE_DESTINATION ?? "data/files"
const HOST = Bun.env.HOST ?? `http://localhost${PORT}`
const MAX_NUMBER_FILE_PER_REQUEST = Bun.env.MAX_NUMBER_FILE_PER_REQUEST ? Math.floor(Number(Bun.env.MAX_NUMBER_FILE_PER_REQUEST)) : 5
const FILE_MAX_SIZE = Bun.env.FILE_MAX_SIZE ? Number(Bun.env.FILE_MAX_SIZE) : 10
const ELASTIC_SEARCH_URL = Bun.env.ELASTIC_SEARCH_URL ?? "http://192.168.150.128:9200"
const ELASTIC_SEARCH_INDEX = Bun.env.ELASTIC_SEARCH_INDEX ?? "bkgpt"

export const ENVIRONMENT = {
  ALLOW_FILE_EXTENSIONS,
  FILE_MAX_SIZE,
  HOST,
  MAX_NUMBER_FILE_PER_REQUEST,
  PORT,
  FILE_DESTINATION,
  ELASTIC_SEARCH_URL,
  ELASTIC_SEARCH_INDEX
}